import { app, BrowserWindow, ipcMain } from 'electron';
import { Agent, AgentInputItem, run } from "@openai/agents";
import { z } from "zod";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// --- Agent Logic ---

const GreetingAgentSchema = z.object({
  greeting: z.string(),
  subtitle: z.string()
});

const assistantAgent = new Agent({
  name: "Greeting Agent",
  instructions: "You are a helpful greeting assistant. Respond with a friendly greeting to the user's input name.",
  model: "gpt-4o-mini", // Using a widely available model
  outputType: GreetingAgentSchema,
});

let conversationHistory: AgentInputItem[] = [];
let totalTokensUsed = 0;
let apiKey = process.env.OPENAI_API_KEY || "";

async function handleUserMessage(userText: string) {
  // Add user message to history
  conversationHistory.push({ role: "user", content: [{ type: "input_text", text: userText }] });

  // Ensure API key is set in env for the SDK
  if (!process.env.OPENAI_API_KEY && apiKey) {
    process.env.OPENAI_API_KEY = apiKey;
  }

  const result = await run(assistantAgent, [...conversationHistory]);

  // Extract reply
  let assistantReply: string;
  if (result.finalOutput && typeof result.finalOutput === "object") {
    // Cast to expected type (Zod validates it at runtime)
    const output = result.finalOutput as { greeting: string, subtitle: string };
    assistantReply = `${output.greeting}\n${output.subtitle}`;
  } else {
    assistantReply = String(result.finalOutput);
  }

  // Update history
  conversationHistory.push({ role: "assistant", content: [{ type: "output_text", text: assistantReply }] });

  // Token usage tracking
  let inputTokens = 0;
  let outputTokens = 0;
  let runTotalTokens = 0;

  if (result.rawResponses) {
    for (const response of result.rawResponses) {
      if (response.usage) {
        inputTokens += response.usage.inputTokens || 0;
        outputTokens += response.usage.outputTokens || 0;
        runTotalTokens += response.usage.totalTokens || 0;
      }
    }
  }

  totalTokensUsed += runTotalTokens;

  return {
    reply: assistantReply,
    usage: {
      prompt: inputTokens,
      completion: outputTokens,
      total: runTotalTokens,
      totalSoFar: totalTokensUsed
    }
  };
}

// --- Electron Main Process ---

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 700,
    width: 900,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false // Security best practice
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

app.on('ready', () => {
  createWindow();

  // IPC Handlers
  ipcMain.handle('has-api-key', () => {
    return !!apiKey;
  });

  ipcMain.handle('save-api-key', (_, key: string) => {
    apiKey = key;
    process.env.OPENAI_API_KEY = key;
    return true;
  });

  ipcMain.handle('agent-message', async (_, userText: string) => {
    if (!apiKey) {
      throw new Error("API key not set. Please provide your OpenAI API key in Settings.");
    }
    try {
      return await handleUserMessage(userText);
    } catch (err: any) {
      console.error("Agent Error:", err);
      throw new Error(err.message || "Failed to get response from agent.");
    }
  });
});

// Quit when all windows are closed, except on macOS.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
